### ISSUE TITLE
Stud.io fails to initialize

### ISSUE THREAD

**Issue by jmcbassett** [fhareide/StudioSubAssemblyHack#1]
I'm using Studio version 2.2.8 (1), and when I replace the original StudioPartDefinition2.txt with your version it crashes on start-up reporting "Failed to initialize Studio (-6)" in normal or administrator modes.

**Comment by fhareide** [comment]
Hmm, that is strange. I have the same version. Did you keep the original file?

**Comment by jmcbassett** [comment]
Indeed

I did keep it, and Studio worked as normal when I reverted to the old file; swap it back to yours again and it fails.  Every time with the old file it works and always fails to initialize with yours.

I did note that my file path is 'C:\Program Files\Studio 2.0 Beta\data' but don't think that'll be an issue.

Thanks 
    Jan

**Comment by fhareide** [comment]
Would you be able to share the original file with me so I can compare with mine?

**Comment by jmcbassett** [comment]
No problem
[StudioPartDefinition2.txt](https://github.com/fhareide/StudioSubAssemblyHack/files/7033293/StudioPartDefinition2.txt)

**Comment by fhareide** [comment]
Yeah, this will not work. Your file is completely different. But if your folder is Studio 2.0 Beta doesn't that mean you have a beta version? I would suggest installing from the Studio site again. You have about 100 parts less in your file.

**Comment by jmcbassett** [comment]
It doesn't report as a beta version now, I think it was when I first installed it.
As you suggest I'll download a new version and see if that works.

**Comment by jmcbassett** [comment]
Clean install done on a different drive but I get the same result, fails to initialize

**Comment by fhareide** [comment]
Sure you are using the correct installer? https://s3.amazonaws.com/blstudio/Studio2.0/Archive/2.2.8_1/Studio+2.0.exe

**Comment by jmcbassett** [comment]
I used the installer on the BrickLink site

**Comment by fhareide** [comment]
Did you figure this out? Did you try the installer I linked?

**Comment by jmcbassett** [comment]
I've fixed the problem.

Following your instructions exactly I only downloaded and replaced the StudioPartDefinition2.txt file in the Studio data folder

Latterly I wondered if the CustomParts folder and CustomParts.png were required; on copying that folder and file to the data folder, Studio started normally and I can adjust the length of the Linear Actuator.

Thanks for your assistance; maybe you can update the installation instructions?

**Comment by jmcbassett** [comment]
p.s. The files from the amazonaws site appears identical to the BrickLink file (the owners).

**Comment by fhareide** [comment]
I think I've already updated the instructions? The CustomParts folder is needed and should be placed under appdata. The path is in the readme. The png is just for the image in the readme and is not needed.

Glad you figured it out! Feel free to ask if you have other questions, but I will close this issue now
